# Generated by Django 4.2.4 on 2023-08-28 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0002_meetup_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name="meetup",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meetups.location",
            ),
        ),
    ]
